version: '3'

services:
  app:
    container_name: ${PROJECT_NAME}_app
    build:
      context: ./.docker
      dockerfile: Dockerfile
      args:
        - IMAGE_VERSION=2.0.0
    image: ${PROJECT_NAME}/application:latest
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "${FORWARD_PORT-3000}:${PORT-3000}"
    volumes:
      - .:/root/app
