version: '3'

services:
  app:
    container_name: ${PROJECT_NAME}_app
    build:
      context: ./.docker
      dockerfile: Dockerfile
      args:
        - IMAGE_VERSION=2.0.0
    image: ${PROJECT_NAME}/application:latest
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "${FORWARD_PORT-3000}:${PORT-3000}"
    volumes:
      - .:/root/app
    networks:
      - backend-network

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "${FORWARD_DB_PORT-27017}:${DB_PORT-27017}"
    networks:
      - backend-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "${FORWARD_MONGO_EXPRESS_PORT-8081}:${MONGO_EXPRESS_PORT-8081}"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
